allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@book000/*'
  - '@sentry/core@10.67.0'
  - '@sentry/node-core@10.67.0'
  - '@sentry/node@10.67.0'
  - '@sentry/opentelemetry@10.67.0'
  - '@sentry/server-utils@10.67.0'
